/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpaceCompact: typeof import('ant-design-vue/es')['Compact']
    ReadAliyunEmail: typeof import('./src/components/aliyun/ReadAliyunEmail.vue')['default']
    ReadAliyunEmail2: typeof import('./src/components/aliyun/ReadAliyunEmail2.vue')['default']
    ReadQQEmail: typeof import('./src/components/qq/ReadQQEmail.vue')['default']
    Svg: typeof import('./src/components/svg/Svg.vue')['default']
  }
}
